### ISSUE TITLE
Things to fix in XRPL4j-v3-dev-preview

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#170]
**Tasks**
- [x] Signature.java is missing JSON serialization annotations.
- [x] Port over Keymetadata codec (and maybe CLI) from interledger4j.
- [x] Create new branches for v2.x backport and v3-dev-preview.
- [x] Add Jackson (de)serializer for `PublicKey` and update unit test for `SignatureWithPublicKeyTest` to check hex values of serialized objects (as opposed to just null-checks)
- [x] Can we add two static constructors to `Signature`: `Signature.of(UnsignedByteArray value)` and `Signature.ofHex(String hexValue)`? Otherwise, you need a `Signature.builder()` just to create a `Signature` which only wraps one value.
- [X] Move all BC code out of `crypto-core` and into `crypto-bc` module (See PR #204).
- [x] Finish test coverage for `UnsignedClaim` signing with KeyMetadata
- [x] #205 
- [x] #209
- [x] `Seed` constructor is `public` but should be package private or `protected`
- [x] Add a way to construct a `Seed` from a Base58 encoded `String` (the thing on the faucet called "secret")
- [x] #211
- [x] #275 
- [x] Move `EcDsaSignature` to be an implementation detail of `BcSignatureService` and then use `BcSignatureService` inside of `SingleKeyDelegatedTransactionSigner` (the signing/verifying logic is duplicated in there). See [PR here](https://github.com/XRPLF/xrpl4j/pull/270).
- [x] Normalize hex `String`s to upper case when using Guava `BaseEncoding.base16()`, such as in `PublicKey`
**WalletFactory/KeyPair Resolution**
- [x] See suggestion [here](https://github.com/XRPLF/xrpl4j/pull/204#discussion_r768197522) and consider making `Ed25519KeyPairService` and `Secp256k1KeyPairService` just implementation details of `BcWalletFactory`.
- [x] Deprecate `AddressUtils` and `WalletFactory`
- [x] Create a typed wrapper object called `Base58EncodedSecret` that is used in `Seed.java` on line 117 (instead of allowing a normal string). We can also assert that the `String` value of `Base58EncodedSecret` is base58 by doing an @Check on the character set. This way it won't be possible to pass-in the wrong value.
- [X] Update to the latest Guava dependency (e.g., [31.1](https://search.maven.org/artifact/com.google.guava/guava/31.1-jre/bundle)) -- see #297 
- [x] Mark the `XrplClient.submit()` that takes a deprecated `SignedTransaction` as also deprecated.
- [x] New `SingleSignedTransaction` class is mistyped -- It is currently named `SingleSingedTransaction` (notice `Singed`)
- [x] Update modules in v3 dev-preview (see #185)

**TODO After Module Condensation**
- [x] Move `UnsignedByteArray` serializer/deserializer into annotation on `UnsignedByteArray` (remove from all `UnsignedByteArray` field definitions (for example - `SignableTransaction.signableTransactionBytes()`). Also un-deprecate `UnsignedByteArray` and remove `core.UnsignedByteArray`. 
- [x] Use correct `UnsignedByteArray` for the `Signature`'s `value` method (not the deprecated one).
- [x] `Signature.value()` uses a `@Deprecated` `UnsignedByteArray` instead of the new `UnsignedByteArray` class.
- [x] Fix #165
- [x] Align the JSON Annotations for `LedgerSpecifier` with `LedgerSpecifierSerializer` (one is snake, the other is camel, but snake is correct)
- [x] Add LedgerIndexBound UNBOUNDED = LedgerIndexBound.of(-1);
- [x] Upgrade okhttp to `4.9.3`
 
**Before Merging to `main`**
- [x] Incorporate any `main` branch additions (e.g., #150, #190, #196, #159, #201 )
- [x] Add MemoIT from v2 ITs in `main` to v3 ITs
- [x] Cleanup Flags.
- [x] Remove all deprecated classes (#365)
- [x]  Promote crypto.core packages (#367)
- [x] All v3 issues ([here](https://github.com/XRPLF/xrpl4j/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.0)).
- [x] Remove all deprecated methods (#366)
- [x] Update licenses for new files that might not have it (#364)

**Version Strategy**
- [x] Release a v2.x.x with all the new v3 code and the deprecated v2 code
- [x] Release a v3.0.0 with all deprecated code deleted

**Comment by sappenin** [comment]
@nkramer44 @florent-uzio

**Comment by nkramer44** [comment]
@sappenin Is the KeyMetadata codec something we want in xrpl4j, or should that live somewhere else?

**Comment by sappenin** [comment]
> @sappenin Is the KeyMetadata codec something we want in xrpl4j, or should that live somewhere else?
Good question - I need to revisit that code, but seems like something that could be useful to anyone using the signing services with KeyMetadata.

Haven't really thought of counter-points, but open to them.

**Comment by nkramer44** [comment]
@sappenin some other things to change:

[] `Signature.value()` uses a `@Deprecated` `UnsignedByteArray` instead of the new `UnsignedByteArray` class.
[] Can we add two static constructors to `Signature`: `Signature.of(UnsignedByteArray value)` and `Signature.ofHex(String hexValue)`? Otherwise, you need a `Signature.builder()` just to create a `Signature` which only wraps one value.

**Comment by sappenin** [comment]
This task is now complete. See [here](https://github.com/XRPLF/xrpl4j/releases/tag/v3.0.0) for more details.
